name : Run Postman Collection workflow
on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: 30 02 * * *
    - cron: 00 14 * * *

jobs:
  run-postman-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout the code
        uses: 	actions/checkout@v6.0.2
        
      - name : Install node
        uses : actions/setup-node@v6.4.0
        with : 
          node-version: '24'
      - name : Install newman and html-extra globally
        run : |
              npm install -g newman
              npm install -g newman-reporter-htmlextra
      - name : Run the postman collection with newman
        run  : |
               newman run 'Inwarranty-flow Collection.postman_collection.json' \
               -e QA.postman_environment.json \
               -d testData.csv \
               -r cli,htmlextra


      - name : Newman Report
        if : always()
        uses: actions/upload-artifact@v7.0.1
        with:
          name : Newman
          path : newman/*.html

      - name : Creating Git hub pages branch
        if : always()
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: newman/
          
      
      
